//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information_Retrieval_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Information_Retrieval_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .I 1
        ///.W
        ///correlation between maternal and fetal plasma levels of glucose and free
        ///fatty acids .                                                           
        ///  correlation coefficients have been determined between the levels of   
        ///glucose and ffa in maternal and fetal plasma collected at delivery .    
        ///significant correlations were obtained between the maternal and fetal   
        ///glucose levels and the maternal and fetal ffa levels . from the size of 
        ///the correlation coefficients and the slopes of regression  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MEDDocuments {
            get {
                return ResourceManager.GetString("MEDDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .I 1
        ///.W
        /// the crystalline lens in vertebrates, including humans.
        ///.I 2
        ///.W
        /// the relationship of blood and cerebrospinal fluid oxygen concentrations
        ///or partial pressures.  a method of interest is polarography.
        ///.I 3
        ///.W
        /// electron microscopy of lung or bronchi.
        ///.I 4
        ///.W
        /// tissue culture of lung or bronchial neoplasms.
        ///.I 5
        ///.W
        /// the crossing of fatty acids through the placental barrier.  normal
        ///fatty acid levels in placenta and fetus.
        ///.I 6
        ///.W
        /// ventricular septal defect occurring in association with  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MEDQueries {
            get {
                return ResourceManager.GetString("MEDQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 0 13 1
        ///1 0 14 1
        ///1 0 15 1
        ///1 0 72 1
        ///1 0 79 1
        ///1 0 138 1
        ///1 0 142 1
        ///1 0 164 1
        ///1 0 165 1
        ///1 0 166 1
        ///1 0 167 1
        ///1 0 168 1
        ///1 0 169 1
        ///1 0 170 1
        ///1 0 171 1
        ///1 0 172 1
        ///1 0 180 1
        ///1 0 181 1
        ///1 0 182 1
        ///1 0 183 1
        ///1 0 184 1
        ///1 0 185 1
        ///1 0 186 1
        ///1 0 211 1
        ///1 0 212 1
        ///1 0 499 1
        ///1 0 500 1
        ///1 0 501 1
        ///1 0 502 1
        ///1 0 503 1
        ///1 0 504 1
        ///1 0 506 1
        ///1 0 507 1
        ///1 0 508 1
        ///1 0 510 1
        ///1 0 511 1
        ///1 0 513 1
        ///2 0 80 1
        ///2 0 90 1
        ///2 0 162 1
        ///2 0 187 1
        ///2 0 236 1
        ///2 0 237 1
        ///2 0 258 1
        ///2 0 289 1
        ///2 0 290 1
        ///2 0 292 1
        ///2  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MEDRelevance {
            get {
                return ResourceManager.GetString("MEDRelevance", resourceCulture);
            }
        }
    }
}
